---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: install alertmaganager
      get_url:
        url: "https://github.com/prometheus/alertmanager/releases/download/v0.20.0/alertmanager-0.20.0.linux-amd64.tar.gz"
        dest: "/etc/alertmanager-0.20.0.linux-amd64.tar.gz"

    - name: extract package
      unarchive:
        src: "/etc/alertmanager-0.20.0.linux-amd64.tar.gz"
        dest: "/usr/local/bin"

    - name: create folder
      file:
        path: "/data/alertmanager"
        state: directory

    - name: edit alertmanager yml
      copy:
        dest: "/usr/local/bin/alertmanager-0.20.0.linux-amd64/alertmanager.yml"
        content: |
          route:
            group_by: [Alertname]
            reciever: email-me
          recievers:
          - name: email-me
            email_configs:
            - to: jack.bartusek@gmail.com
              from: jack.bartusek@gmail.com
              smarthost: smtp.gmail.com:587
              auth_username: "jack.bartusek@gmail.com"
              auth_identity: "jack.bartusek@gmail.com"
              auth_password: ""

    - name: create service file
      file:
        path: "/lib/systemd/system/alertmanager.service"
        state: touch

    - name: fill service file
      copy:
        dest: "/lib/systemd/system/alertmanager.service"
        content: |
          [Unit]
          Description=Alert Manager
          Wants=network-online.target
          After=network-online.target
          [Service]
          Type=simple
          User=root
          Group=root
          ExecStart=/usr/local/bin/alertmanager \
            --config.file=/usr/local/bin/alertmanager.yml \
            --storage.path=/data/alertmanager
          Restart=always
          [Install]
          WantedBy=multi-user.target

    - name: bind alertmanager with prom
      copy:
        dest: "/var/lib/docker/volumes/prometheus_conf/_data/prometheus.yml"
        content: |
          global:
            scrape_interval: 15s
            evaluation_interval: 15s
          alerting:
            alertmanagers:
              - static_configs:
                - targets:
                  - localhost:9093
          rule_files:
            - "myrules.yml"
          scrape_configs:
            - job_name: "prometheus"
              static_configs:
                - targets: ["0.0.0.0:9090"]
            - job_name: "docker"
              static_configs:
                - targets: ["192.168.0.107:9323"]

    - name: create myrule file
      file:
        path: "/var/lib/docker/volumes/prometheus_conf/_data/myrules.yml"
        state: touch

    - name: fill myrule file
      copy:
        dest: "/var/lib/docker/volumes/prometheus_conf/_data/myrules.yml"
        content: |
          groups:
            - name: test
              rules:
              - alert: instance down
                expr: up == 0
                for: 1m
