--- 
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: create grafana container
      docker_container:
        name: grafana
        image: grafana/grafana:latest
        state: started
        ports:
          - "3000:3000"
        volumes:
          - "grafana_config:/etc/grafana"
          - "grafana_data:/var/lib/grafana"
          - "grafana_logs:/var/log/grafana"
