---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: install firewalld
      apt:
        name: firewalld
        state: latest

    - name: create json file
      file:
        path: "/etc/docker/daemon.json"
        state: touch

    - name: enable traffic in firewall
      firewalld:
        port: 9323/tcp
        permanent: yes
        state: enabled

    - name: fill json file
      copy:
        dest: "/etc/docker/daemon.json"
        content: |
          {
          "metrics-addr" : "0.0.0.0:9323",
          "experimental" : true
          }

    - name: create prometheus container
      docker_container:
        image: prom/prometheus:latest
        name: prometheus
        state: started
        ports:
          - "9090:9090"
        volumes:
          - "prometheus_conf:/etc/prometheus"

    - name: add docker to endpoints
      copy: 
        dest: "/var/lib/docker/volumes/prometheus_conf/_data/prometheus.yml"
        content: | 
          global:
            scrape_interval: 15s
            evaluation_interval: 15s
          alerting:
            alertmanagers:
              - static_configs:
                  - targets:
                    #- alertmanager:9093
          rule_files:
          scrape_configs:
            - job_name: "prometheus"
              static_configs:
                - targets: ["0.0.0.0:9090"]
            - job_name: "docker"
              static_configs:
                - targets: ["192.168.0.107:9323"]
    
    - name: restart prometheus
      docker_container:
        name: prometheus
        state: started
        restart: yes
