---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: create container
      docker_container:
        name: reverse-proxy
        image: nginx:latest
        ports:
          - "80:80"


sudo docker cp reverse-proxy:/etc/nginx/conf.d/default.conf ~/Desktop/default.conf


sudo nano ~/Desktop/default.conf


---
upstream testtest {
    server localhost:8080;
}

server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /test {
        proxy_pass http://testtest/test;
    }
    
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}---



sudo docker cp ~/Desktop/default.conf reverse-proxy:/etc/nginx/conf.d/


sudo docker exec reverse-proxy nginx -s reload
